{% set name = "sphinx-inline-tabs" %}
{% set version = "2021.4.11b9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_inline_tabs-{{ version }}.tar.gz
  sha256: 09267b9980b405bada41e63f9912769a394731e0e015068cda7feab1a13f8fe5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core >=2,<4   
  run:
    - python >=3.6
    - beautifulsoup4
    - sphinx >3 

test:
  imports:
    - sphinx_inline_tabs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pradyunsg/sphinx-inline-tabs
  summary: Add inline tabbed content to your Sphinx documentation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
